"""Create GitHub issues for verdicts requiring human review.

M4 Task 15: Auto-create GitHub issues for FAIL, MANUAL_REVIEW, and
INSUFFICIENT_EVIDENCE verdicts using PyGithub.
"""

from __future__ import annotations

from datetime import date
from pathlib import Path
from typing import TYPE_CHECKING

from loguru import logger

try:
    from github import Github  # type: ignore[import-untyped]

    _PYGITHUB_AVAILABLE = True
except ImportError:
    Github = None  # type: ignore[assignment,misc]
    _PYGITHUB_AVAILABLE = False

if TYPE_CHECKING:
    from .config import AuditorSettings
    from .models import Verdict

# Statuses that require human attention — issues are created for these.
_REVIEW_STATUSES = {"FAIL", "MANUAL_REVIEW", "INSUFFICIENT_EVIDENCE"}

# Status → label suffix
_STATUS_LABEL: dict[str, str] = {
    "FAIL": "privacy-fail",
    "MANUAL_REVIEW": "privacy-review",
    "INSUFFICIENT_EVIDENCE": "privacy-insufficient",
}

# Status → emoji prefix for issue title section header
_STATUS_EMOJI: dict[str, str] = {
    "FAIL": "🔴",
    "MANUAL_REVIEW": "🟡",
    "INSUFFICIENT_EVIDENCE": "🟠",
}

# Status → human-readable label for section header
_STATUS_LABEL_DISPLAY: dict[str, str] = {
    "FAIL": "FAIL",
    "MANUAL_REVIEW": "Manual Review Required",
    "INSUFFICIENT_EVIDENCE": "Insufficient Evidence",
}

# Status → action required paragraph
_ACTION_TEXT: dict[str, str] = {
    "FAIL": (
        "This claim was found to **contradict** the code evidence. The privacy policy "
        "or the code needs to be updated to resolve this discrepancy."
    ),
    "MANUAL_REVIEW": (
        "This claim requires human assessment. Automated evidence gathering could not "
        "conclusively verify or refute this claim."
    ),
    "INSUFFICIENT_EVIDENCE": (
        "Not enough evidence was found. Consider adding tests or documentation to make "
        "this claim verifiable."
    ),
}

# Maximum characters for claim text in issue title.
_TITLE_MAX_CLAIM_LEN = 60

# Maximum evidence items to show in issue body.
_MAX_EVIDENCE_IN_BODY = 3


def _truncate_claim(text: str, max_len: int = _TITLE_MAX_CLAIM_LEN) -> str:
    """Truncate claim text to max_len chars, appending '...' if truncated."""
    if len(text) <= max_len:
        return text
    return text[:max_len] + "..."


def _build_issue_title(status: str, claim_text: str) -> str:
    """Build the issue title string."""
    truncated = _truncate_claim(claim_text)
    return f"[Privacy Audit] {status}: {truncated}"


def _build_issue_body(
    verdict: Verdict,
    claim_text: str,
    target_commit: str,
    cert_path: Path | None,
) -> str:
    """Render the Markdown body for a GitHub issue."""
    status = verdict.status
    emoji = _STATUS_EMOJI.get(status, "⚪")
    display = _STATUS_LABEL_DISPLAY.get(status, status)
    action = _ACTION_TEXT.get(status, "Manual review required.")

    # Short commit reference (first 12 chars)
    short_commit = target_commit[:12] if target_commit != "unknown" else "unknown"

    # Audit date
    audit_date = date.today().isoformat()

    # Claim summary (first 120 chars for the header)
    claim_summary = claim_text[:120] + ("..." if len(claim_text) > 120 else "")

    # Top evidence items
    evidence_items = verdict.evidence[:_MAX_EVIDENCE_IN_BODY]
    evidence_md_lines: list[str] = []
    for i, ev in enumerate(evidence_items, 1):
        snippet_preview = ev.snippet[:200].replace("\n", " ").strip()
        evidence_md_lines.append(
            f"{i}. **`{ev.file_path}:{ev.start_line}-{ev.end_line}`**\n"
            f"   ```\n   {snippet_preview}\n   ```"
        )
    evidence_md = (
        "\n".join(evidence_md_lines)
        if evidence_md_lines
        else "_No evidence collected._"
    )

    # Certification reference
    if cert_path is not None:
        cert_ref = str(cert_path)
    else:
        cert_ref = "certifications/<target>/<timestamp>/certification.md"

    lines = [
        f"## {emoji} Privacy Audit: {display} — {claim_summary}",
        "",
        f"**Claim:** {claim_text}",
        f"**Verdict:** {status} (confidence: {verdict.confidence:.0%})",
        f"**Audit Date:** {audit_date}",
        f"**Target Commit:** `{short_commit}`",
        "",
        "### Judge's Reasoning",
        verdict.reasoning,
        "",
        "### Key Evidence",
        evidence_md,
        "",
        "### Action Required",
        action,
        "",
        "### Audit Reference",
        f"- Certification: `{cert_ref}`",
        f"- Claim ID: `{verdict.claim_id}`",
        "",
        "---",
        "*Generated by mcp-vector-search privacy auditor*",
    ]
    return "\n".join(lines)


def _ensure_labels(repo: object, labels_needed: list[str]) -> None:
    """Create any missing labels on the repo (best-effort, logs on failure)."""
    label_colors = {
        "privacy-audit": "0075ca",
        "privacy-fail": "d73a4a",
        "privacy-review": "e4e669",
        "privacy-insufficient": "f9d0c4",
    }
    try:
        existing = {lbl.name for lbl in repo.get_labels()}  # type: ignore[union-attr]
        for label_name in labels_needed:
            if label_name not in existing:
                color = label_colors.get(label_name, "ededed")
                try:
                    repo.create_label(name=label_name, color=color)  # type: ignore[union-attr]
                    logger.debug("Created GitHub label: %s", label_name)
                except Exception as exc:  # noqa: BLE001
                    logger.warning("Could not create label '%s': %s", label_name, exc)
    except Exception as exc:  # noqa: BLE001
        logger.warning("Could not list existing labels: %s", exc)


def _parse_owner_repo(
    target_repo: str, github_repo_setting: str | None
) -> tuple[str, str] | None:
    """Extract (owner, repo) from a repo path/URL or settings string.

    Priority:
    1. github_repo_setting (format: owner/repo)
    2. Parse target_repo as a GitHub URL or slug
    """
    if github_repo_setting:
        parts = github_repo_setting.strip().split("/")
        if len(parts) >= 2:
            return parts[-2], parts[-1]

    # Try to parse target_repo as a URL-like or slug
    cleaned = target_repo.strip().rstrip("/")
    # Handle https://github.com/owner/repo[.git]
    if "github.com" in cleaned:
        after = cleaned.split("github.com/", 1)[-1]
        after = after.removesuffix(".git")
        parts = after.split("/")
        if len(parts) >= 2:
            return parts[0], parts[1]
    # Handle owner/repo slug (no path separators that look like filesystem paths)
    if cleaned.count("/") == 1 and not cleaned.startswith("/"):
        owner, repo = cleaned.split("/", 1)
        return owner, repo

    return None


async def create_review_issues(
    verdicts: list[Verdict],
    target_repo: str,
    target_commit: str,
    settings: AuditorSettings,
    cert_path: Path | None = None,
) -> list[dict]:
    """Create GitHub issues for FAIL, MANUAL_REVIEW, and INSUFFICIENT_EVIDENCE verdicts.

    Skips PASS and IGNORED verdicts. Deduplicates by searching for existing
    open issues containing the claim_id before creating new ones.

    Args:
        verdicts: All verdict objects from the audit run.
        target_repo: Repository path or URL being audited.
        target_commit: Commit SHA that was audited.
        settings: AuditorSettings with github_token and github_repo.
        cert_path: Optional path to the certification.md file for cross-referencing.

    Returns:
        List of dicts: {"issue_number": N, "url": "...", "claim_id": "...", "status": "created"|"updated"}
    """
    if not settings.create_issues:
        logger.debug("Issue creation disabled (create_issues=False)")
        return []

    token = settings.github_token
    if not token or not token.get_secret_value():
        logger.warning(
            "No GitHub token configured. Set MVS_AUDIT_GITHUB_TOKEN or GITHUB_TOKEN "
            "to enable automatic issue creation."
        )
        return []

    owner_repo = _parse_owner_repo(target_repo, settings.github_repo)
    if owner_repo is None:
        logger.warning(
            "Could not determine GitHub owner/repo. Set MVS_AUDIT_GITHUB_REPO=owner/repo "
            "to enable automatic issue creation."
        )
        return []

    owner, repo_name = owner_repo

    if not _PYGITHUB_AVAILABLE or Github is None:
        logger.warning(
            "PyGithub not installed. Install with: pip install 'PyGithub>=2.3.0'"
        )
        return []

    gh = Github(token.get_secret_value())
    try:
        repo = gh.get_repo(f"{owner}/{repo_name}")
    except Exception as exc:  # noqa: BLE001
        logger.warning("Could not access GitHub repo %s/%s: %s", owner, repo_name, exc)
        return []

    results: list[dict] = []

    # Filter to only verdicts that need issues (not PASS, not IGNORED)
    review_verdicts = [
        v for v in verdicts if not v.ignored and v.status in _REVIEW_STATUSES
    ]

    if not review_verdicts:
        logger.debug("No verdicts requiring GitHub issues.")
        return []

    # Collect all labels we'll need and ensure they exist
    labels_needed = ["privacy-audit"]
    for v in review_verdicts:
        status_label = _STATUS_LABEL.get(v.status)
        if status_label:
            labels_needed.append(status_label)
    _ensure_labels(repo, list(dict.fromkeys(labels_needed)))  # dedupe, preserve order

    for verdict in review_verdicts:
        claim_id = verdict.claim_id
        # Use first 60 chars of claim_id as a stand-in for the claim text
        # (we don't have the PolicyClaim here, so use claim_id for dedup search)
        # The actual claim text comes from the verdict's reasoning context.
        # We use the reasoning as the claim text proxy for the title.
        claim_text = _extract_claim_text(verdict)

        title = _build_issue_title(verdict.status, claim_text)
        body = _build_issue_body(verdict, claim_text, target_commit, cert_path)

        issue_labels = ["privacy-audit"]
        status_label = _STATUS_LABEL.get(verdict.status)
        if status_label:
            issue_labels.append(status_label)

        # Deduplicate: search for existing open issues with this claim_id
        existing_issue = _find_existing_issue(repo, claim_id)

        if existing_issue is not None:
            # Add a comment updating status instead of creating a duplicate
            try:
                comment_body = (
                    f"**Privacy Audit Update**\n\n"
                    f"This claim was re-audited.\n\n"
                    f"**New Verdict:** {verdict.status} (confidence: {verdict.confidence:.0%})\n\n"
                    f"**Reasoning:** {verdict.reasoning}\n\n"
                    f"*Updated by mcp-vector-search privacy auditor*"
                )
                existing_issue.create_comment(comment_body)
                logger.info(
                    "Updated existing issue #%d for claim %s",
                    existing_issue.number,
                    claim_id,
                )
                results.append(
                    {
                        "issue_number": existing_issue.number,
                        "url": existing_issue.html_url,
                        "claim_id": claim_id,
                        "status": "updated",
                    }
                )
            except Exception as exc:  # noqa: BLE001
                logger.warning(
                    "Could not comment on issue #%d: %s", existing_issue.number, exc
                )
        else:
            # Create a new issue
            try:
                create_kwargs: dict = {
                    "title": title,
                    "body": body,
                    "labels": issue_labels,
                }
                if settings.reviewer:
                    create_kwargs["assignees"] = [settings.reviewer]

                new_issue = repo.create_issue(**create_kwargs)
                logger.info(
                    "Created GitHub issue #%d for claim %s (%s)",
                    new_issue.number,
                    claim_id,
                    verdict.status,
                )
                results.append(
                    {
                        "issue_number": new_issue.number,
                        "url": new_issue.html_url,
                        "claim_id": claim_id,
                        "status": "created",
                    }
                )
            except Exception as exc:  # noqa: BLE001
                logger.warning("Could not create issue for claim %s: %s", claim_id, exc)

    return results


def _extract_claim_text(verdict: Verdict) -> str:
    """Extract a human-readable claim text from a verdict.

    Since Verdict doesn't carry the original claim text, we derive a
    short summary from the claim_id and reasoning. The claim_id is the
    primary dedup key; the reasoning provides context for the title.
    """
    # Use a short prefix from reasoning as the "claim text" for display
    reasoning = verdict.reasoning.strip()
    # Strip common prefixes like "Evidence supports PASS." or "Ignored: ..."
    for prefix in ("Evidence supports ", "Ignored: ", "Claim ", "The claim "):
        if reasoning.startswith(prefix):
            reasoning = reasoning[len(prefix) :]
            break
    # Use first sentence or 80 chars
    first_sentence_end = reasoning.find(". ")
    if 0 < first_sentence_end < 80:
        return reasoning[: first_sentence_end + 1]
    return reasoning[:80]


def _find_existing_issue(repo: object, claim_id: str) -> object | None:
    """Search for an existing open issue mentioning the claim_id.

    Returns the first matching issue object, or None if not found.
    """
    try:
        issues = repo.get_issues(state="open")  # type: ignore[union-attr]
        for issue in issues:
            if claim_id in (issue.body or ""):
                return issue
    except Exception as exc:  # noqa: BLE001
        logger.debug("Could not search existing issues: %s", exc)
    return None
